# -*- coding: utf-8 -*-
"""CNN_Mnist

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bNfIcMHtXzYb-rG2CIVi69CYiMsQLxRC
"""

import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
from mlxtend.data import loadlocal_mnist
from tensorflow.keras.datasets import mnist
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

mnist = tf.keras.datasets.mnist

(X_train,y_train),(X_test,y_test) = mnist.load_data()

print(f"Training data size is {X_train.shape}\nTesting data size is {X_test.shape}")

X_train = X_train.reshape((60000, 28, 28, 1))
#X_test = X_test.reshape((10000, 28, 28, 1))

X_train = X_train.astype(float)/ 255.0
X_test = X_test.astype(float)/ 255.0

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Dropout(0.2))
model.add(layers.Flatten())
model.add(layers.Dense(10, activation='softmax'))

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy'])

X_train.shape

y_train.shape

model.fit(X_train, y_train, epochs=15, batch_size=1000)

X_test[0]

test_loss, test_acc = model.evaluate(X_test,  y_test, verbose=2)

pred = model.predict(X_test[0].reshape(1,28,28)).argmax(axis=1)

print(pred)

import matplotlib.pyplot as plt

plt.imshow(X_test[0])

"""IMPORT DATA"""

import cv2
from keras.preprocessing.image import img_to_array

from google.colab import drive
drive.mount('/content/drive')

img = cv2.imread('/content/drive/MyDrive/dataPTDL/Mnist_Test/Mnist_test/8.png')
img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img = cv2.resize(img,(28,28))
plt.imshow(img)
img = img_to_array(img)
img = img.reshape(1,28,28)

pred_main = model.predict(img).argmax(axis = 1)
f"{int(pred_main)}"

# model.save('/content/drive/MyDrive/Study/Model_Colab/CNN_Mnist.model')